# This is a basic workflow to help you get started with Actions

name: create-snapshot

on:
  push:
    branches:
      - master

jobs:
  build-jar:
    runs-on: [windows-latest]

    steps:
    - name: Get the repo content
      uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'gradle'
    - name: Build with Gradle
      run: .\gradlew.bat dist --no-daemon
    - name: Create Distribution   
      run: distribution\create-distribution-jar.bat SNAPSHOT-$(date +"%Y%m%d_%H%M00")   
    - uses: AButler/upload-release-assets@v2.0
      with:
          files: './distribution/freerouting-SNAPSHOT-*.jar'
          release-tag: SNAPSHOT
          repo-token: ${{ secrets.GITHUB_TOKEN }}      
