name: gradle-build-on-pr

on: [pull_request,  workflow_dispatch, commit]

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v3 
      with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: build
